version: "3.7"

networks:
  analytics-net:
    external: true

services:

  kafkainit:
    build: 
      dockerfile: ../images/Dockerfile
      context: .
    volumes: 
      - ${TOPICS_FILE}:/usr/share/apps/scripts/topics.json
    environment:
      KAFKA_HOST: "kafka"
      KAFKA_PORT: 19092
    networks: 
      - analytics-net
    command: "python3 create_topics.py"

  druidinit:
    build: 
      dockerfile: ../images/Dockerfile
      context: .
    volumes: 
      - ${SPEC_PATH}:/specs/
    environment:
      DRUID_URL: "coordinator:8081"
    networks: 
      - analytics-net
    command: "python3 create_supervisors.py"

  adaptors:
    build: 
      dockerfile: ../images/Dockerfile.adaptors
      context: .
    volumes: 
      - ${ADAPTORS_PATH}:/adaptors/
      - ${CONFIG_FILE}:/config.json
    networks: 
      - analytics-net


