version: "3.7"

volumes:
  metadata_data: {}
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  router_var: {}

networks:
  analytics-net:
    external: true

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - metadata_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=somepassword
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid
    networks: 
      - analytics-net


  coordinator:
    image: apache/druid:0.20.2
    container_name: coordinator
    volumes:
      - ./storage:/opt/data
      - coordinator_var:/opt/druid/var
    depends_on: 
      - postgres
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - ./coord.env
      - ./environment
    networks: 
      - analytics-net

  broker:
    image: apache/druid:0.20.2
    container_name: broker
    volumes:
      - broker_var:/opt/druid/var
    depends_on: 
      - postgres
      - coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - ./broker.env
      - environment
    networks: 
      - analytics-net

  historical:
    image: apache/druid:0.20.2
    container_name: historical
    volumes:
      - ./storage:/opt/data
      - historical_var:/opt/druid/var
    depends_on: 
      - postgres
      - coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - ./historical.env
      - environment
    networks: 
      - analytics-net

  middlemanager:
    image: apache/druid:0.20.2
    container_name: middlemanager
    volumes:
      - ./storage:/opt/data
      - middle_var:/opt/druid/var
    depends_on: 
      - postgres
      - coordinator
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - middleManager
    env_file:
      - ./mm.env
      - ./environment
    networks: 
      - analytics-net

  router:
    image: apache/druid:0.20.2
    container_name: router
    volumes:
      - router_var:/opt/druid/var
    depends_on:
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - ./router.env
      - environment
    networks: 
      - analytics-net
